# Generated by Django 5.2.2 on 2025-06-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageProcessingResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blob_bucket", models.CharField(max_length=255)),
                ("blob_file_name", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processor.imagemodel",
                    ),
                ),
            ],
        ),
    ]
