# Generated by Django 5.2.2 on 2025-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processor", "0002_imageprocessingresults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageprocessingresults",
            name="blob_bucket",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
