# Generated by Django 5.2.2 on 2025-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processor", "0003_alter_imageprocessingresults_blob_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageprocessingresults",
            name="blob_bucket",
            field=models.CharField(default="thumbnails", max_length=255),
        ),
        migrations.AlterField(
            model_name="imageprocessingresults",
            name="blob_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
