# Generated by Django 5.2.2 on 2025-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_uploadfile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(max_length=255, upload_to="uploads/"),
        ),
    ]
