# Generated by Django 5.2.2 on 2025-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_alter_uploadfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(max_length=255, upload_to="images/"),
        ),
    ]
